version: "3"
services:
  tasks:
    image: taskbot:latest
    restart: unless-stopped
    container_name: taskbot
    volumes:
        - "./config.json:/config.json"
        - "./db.sqlite:/db.sqlite"