version: "3"
services:
  taskerbot:
    image: mohsenjfar/taskerbot:latest
    restart: unless-stopped
    container_name: taskerbot
    volumes:
        - "./config.json:/root/config.json"
        - "./db.sqlite:/root/db.sqlite"