version: "3"
services:
  tasks:
    image: mohsenjfar/taskerbot:latest
    restart: unless-stopped
    container_name: taskerbot
    volumes:
        - "./telegram/config.json:/taskerbot/telegram/config.json"
        - "./db.sqlite3:/taskerbot/db.sqlite3"